# adapters/base.py
"""平台适配器抽象接口"""
from abc import ABC, abstractmethod
from typing import Callable, List, Optional, Any, Dict

class IFrameworkAdapter(ABC):
    @abstractmethod
    def send_game_command(self, cmd: str) -> None: ...
    @abstractmethod
    def send_game_message(self, target: str, text: str) -> None: ...
    @abstractmethod
    def get_online_players(self) -> List[str]: ...
    @abstractmethod
    def send_group_msg(self, group_id: int, message: str) -> bool: ...
    @abstractmethod
    def send_private_msg(self, user_id: int, message: str) -> bool: ...
    @abstractmethod
    def listen_game_chat(self, handler: Callable[[str, str], None]) -> None: ...
    @abstractmethod
    def listen_group_message(self, handler: Callable[[Dict[str, Any]], None]) -> None: ...
    @abstractmethod
    def listen_player_join(self, handler: Callable[[str], None]) -> None: ...
    @abstractmethod
    def listen_player_leave(self, handler: Callable[[str], None]) -> None: ...
    @abstractmethod
    def register_console_command(self, triggers: List[str], hint: str, usage: str,
                                 func: Callable) -> None: ...
    @abstractmethod
    def get_plugin_api(self, name: str) -> Optional[Any]: ...
    @abstractmethod
    def is_user_admin(self, user_id: int, config_mgr) -> bool: ...